apiVersion: v1

-------------------------------------------------------------------
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://FB2C883831FCE487C5D32D12B14665F0.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:686766985335:cluster/my-cluster1

- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://EB8834081FD889D10E9EBBA65833F7AE.gr7.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:686766985335:cluster/my-eks-cluster

- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop

- cluster:
    certificate-authority: C:\Users\KALI\.minikube\ca.crt
    server: https://172.19.11.225:8443
  name: minikube

-------------------------------------------------------------------

contexts:
- context:
    cluster: arn:aws:eks:us-west-2:686766985335:cluster/my-cluster1
    user: arn:aws:eks:us-west-2:686766985335:cluster/my-cluster1
  name: arn:aws:eks:us-west-2:686766985335:cluster/my-cluster1

- context:
    cluster: arn:aws:eks:us-west-2:686766985335:cluster/my-eks-cluster
    user: arn:aws:eks:us-west-2:686766985335:cluster/my-eks-cluster
  name: arn:aws:eks:us-west-2:686766985335:cluster/my-eks-cluster

- context:
    cluster: minikube
    namespace: batch29
    user: minikube
  name: batch29

- context:
    cluster: minikube
    namespace: team-a
    user: minikube
  name: batchgfg23

- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop

----current context----
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube
----current context----

- context:
    cluster: minikube
    namespace: pranjal
    user: minikube
  name: pranjalcontext

- context:
    cluster: minikube
    namespace: teama
    user: minikube
  name: teama

- context:
    cluster: minikube
    namespace: customera
    user: minikube
  name: customera

-------------------------------------------------------------------

current-context: minikube

kind: Config

preferences: {}

users:
- name: arn:aws:eks:us-west-2:686766985335:cluster/my-cluster1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - my-cluster1
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false

- name: arn:aws:eks:us-west-2:686766985335:cluster/my-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - my-eks-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false

- name: docker-desktop
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
    
- name: minikube
  user:
    client-certificate: C:\Users\KALI\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\KALI\.minikube\profiles\minikube\client.key